//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class building
    {
        public building()
        {
            this.rooms = new HashSet<room>();
        }
    
        public int building_id { get; set; }
        public string building_name { get; set; }
    
        public virtual ICollection<room> rooms { get; set; }
    }
}
