//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class direction
    {
        public direction()
        {
            this.groups = new HashSet<group>();
        }
    
        public string direction_name { get; set; }
        public int direction_id { get; set; }
    
        public virtual ICollection<group> groups { get; set; }
    }
}
