//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_assignments
    {
        public int group_assignment_id { get; set; }
        public int class_assignment_id { get; set; }
        public int group_id { get; set; }
        public Nullable<int> subgroup_id { get; set; }
    
        public virtual class_assignments class_assignments { get; set; }
        public virtual group group { get; set; }
    }
}
