//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.class_assignments = new HashSet<class_assignments>();
        }
    
        public int room_id { get; set; }
        public int building_id { get; set; }
        public int room_number { get; set; }
    
        public virtual building building { get; set; }
        public virtual ICollection<class_assignments> class_assignments { get; set; }
    }
}
