//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public teacher()
        {
            this.class_assignments = new HashSet<class_assignments>();
        }
    
        public int teacher_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
    
        public virtual ICollection<class_assignments> class_assignments { get; set; }
    }
}
